from pydantic import BaseModel
from typing import List, Optional, Dict

class User(BaseModel):
    user_id: int
    user_name: str
    name: str
    age: int
    gender: str
    height: int
    weight: int
    primary_health_goals: str
    flavor_preferences: str
    cuisine_preferences: str
    dietary_preferences: str
    total_budget: str
    meal_budget: str
    allergies_restrictions: str
    meal_frequency: str
    meal_types: str
    eating_time: str
    activity_level: str
    target_weight: int
    goal_timeline: str
    workout_days: str

class Dish(BaseModel):
    name: str
    description: Optional[str]
    dish_id: Optional[str]
    user_id: Optional[str]
    user_name: Optional[str]

class Dish_Details(BaseModel):
    dish_res_id: Optional[str]
    dish_id: Optional[str]
    restaurant_id: Optional[str]
    _additional: Optional[Dict]
    geo_coordinates: Optional[int]
    dish_name: Optional[str]
    calorie_count_estimate: Optional[str]
    cleaned_dish_name: Optional[str]
    diet_tags: Optional[List[str]]
    food_item_link_uber: Optional[str]
    food_item_link_door_dash: Optional[str]
    food_item_uber_cart_links: Optional[str]
    health_alternatives: Optional[str]
    mass_carbs: Optional[str]
    mass_fat: Optional[str]
    mass_protein: Optional[str]
    image_door_dash: Optional[str]
    image_uber: Optional[str]
    link_uber: Optional[str]
    link_door_dash: Optional[str]
    price_clean: Optional[str]
    close_time_uber_eats_uber: Optional[str]
    days_open_uber_eats_uber: Optional[str]
    monday_door_dash: Optional[str]
    tuesday_door_dash: Optional[str]
    wednesday_door_dash: Optional[str]
    thursday_door_dash: Optional[str]
    friday_door_dash: Optional[str]
    saturday_door_dash: Optional[str]
    sunday_door_dash: Optional[str]
    lat: Optional[float]
    long: Optional[float]
    neighborhood: Optional[str]
    open_close_hours: Optional[str]
    opening_hours_uber_eats_uber: Optional[str]
    restaurant_name: Optional[str]
    restaurant_phone: Optional[str]
    restaurant_rating: Optional[str]
    restaurant_review_count: Optional[int]
    eater_review_dict_vec: Optional[Dict]
    infatuation_review_dict_vec: Optional[Dict]

class DoorDash_Schedule(BaseModel):
    monday: Optional[str]
    tuesday: Optional[str]
    wednesday: Optional[str]
    thursday: Optional[str]
    friday: Optional[str]
    saturday: Optional[str]
    sunday: Optional[str]